[tools]
dprint = "latest"
pre-commit = "latest"

[tasks.pre-commit-all]
description = "Run pre-commit hooks on all files"
alias = "p"
run = "pre-commit run -a"

[tasks.pre-commit-update]
description = "Update pre-commit hooks to the latest versions"
run = "pre-commit autoupdate"
